### ISSUE TITLE
Podfile not found

### ISSUE THREAD

**Issue by Kibukita** [bitrise-steplib/steps-cocoapods-install#58]
Hi, I am developing a ios Cordova app from Windows. I need to use Push Notifications, so I have added **phonegap-plugin-push** to my project and **Run Coocoapods** as step in my workflow but I get an error and I cannot build my app:

`No `Podfile' found in the project directory`

Nevertheless I set the path to PodFile in the Cocoapods step and in fact, Podfile is found at the beginning of the step:

```
Configs:
- SourceRootPath: /Users/vagrant/git
- PodfilePath: /Users/vagrant/git/platforms/ios/
- IsUpdateCocoapods: false
- InstallCocoapodsVersion: 
- Verbose: true
- IsCacheDisabled: false
Using Podfile: /Users/vagrant/git/platforms/ios
```
I am very newbie with Cocoapods, so I appreciate so much your help, this is my build: https://app.bitrise.io/build/97c843e6493b3145

Thanks so much in advance.

**Comment by non-binary** [comment]
Hi @Kibukita,

Please enable support access by going to your project settings.

**Comment by Kibukita** [comment]
Done! I have solved the problem installing phonegap-plugin-push and CocoaPods from script step but In any case I would like to know what the problem is for future projects.
Thanks in advance.

**Comment by non-binary** [comment]
Hi @Kibukita,

This error occurs when the Podfile can't be found because it is looking in the wrong place. Or in this case, it did not exist because the native project had not been generated. Given you are keeping it in the Cordova land without the native project being generated, it is unnecessary.

Please don't hesitate to follow-up if you have any other questions.
